name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint, test, build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci --includes=dev

      - name: Linter
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: tsc
